---
title: "Hypoxic and Eutrophic map"
author: "Jamie Afflerbach"
date: "1/18/2019"
output: html_document
---


## Setup

```{r setup, message = F, warning = F}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)

library(tidyverse)
library(sf)
library(raster)
library(tmap)
library(RColorBrewer)
library(readxl)

#point to aquaculture folder on aurora
dir_a <- c('Windows' = '//aurora.nceas.ucsb.edu/aquaculture',
           'Darwin'  = '/Volumes/aquaculture',    
           'Linux'   = '/home/shares/aquaculture')[[ Sys.info()[['sysname']] ]]

#set rainbow color scheme
cols      = colorRampPalette(brewer.pal(9, 'Spectral'))(255) # rainbow color scheme
```

Read in hypoxic eutrophic site

```{r}
sites <- read_excel("~/github/seaweed/Data/wri_eutrophic_hypoxic_dataset_2011-03.xls")

#filter for decade 2000
sites_2000 <- sites %>%
  mutate(category = ifelse(Classification == "eutrophic", "Eutrophic", Classification)) %>%
  filter(!category %in% c("Improved", "improved"))
```

Create `sf` object

```{r}
sites_sf <- st_as_sf(sites_2000,coords = c("Long", "Lat"), crs = 4326) %>%
  st_transform(crs = "+proj=moll +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs")
```

Load OA map

```{r}
oa <- raster(file.path(dir_a, "ARF/oa/global_arag_avg_moll_2016.tif"))
# ocean <- raster(file.path(dir_a, "ARF/oa/ocean.tif")) %>% #ocean raster at 1km touse for mask
#           resample(oa)
  
#interpolate across NA
xy <- data.frame(xyFromCell(oa, 1:ncell(oa)))                         #get xy coords into dataframe
v  <- getValues(oa)                                                   #get cell values 
tmpdf <- cbind(xy, v)%>%filter(!is.na(v))                             #create dataframe of x,y, and values. remove NAs (throws error since these are cells we are interpolating over)
mg <- gstat::gstat(id = "v", formula = v~1, locations = ~x+y, data=tmpdf,
            nmax=7, set=list(idp = 2)) #define model. power function = 2, this is default for idw models
oa_int <- interpolate(oa, mg, progress='text')  
oa_mask <- mask(oa_int, ocean)

oa_mask[oa_mask>3.05]<-NA #using 3.05 to get contour lines for Aragonite values at 3
```


Get world map

```{r}
#grab the worldmap from rnaturalearth
worldmap <- rnaturalearth::ne_download(scale = 110,
                                       type = "countries",
                                       category = "cultural",
                                       destdir = tempdir(),
                                       load = TRUE,
                                       returnclass = "sf")
```


```{r}
# #get contour lines
# levels <- c(1,2,3)
# oa_cont <- rasterToContour(oa, levels = levels, drawLabels = T)

#make map
hyp_eut_map <- 
  tm_shape(oa_mask) +
  tm_raster(palette = "RdYlBu", style = "cont", title = "Ω (aragonite \nsaturation state)") +
  # tm_shape(oa_cont) +
  # tm_lines() +
  tm_shape(worldmap) +
  tm_polygons(col = "ivory", lwd = 0.5, alpha = 0.85) +
  tm_shape(sites_sf) +
  tm_symbols(col = "category", border.col = "black", border.lwd = 0.3, 
             size = 0.05, alpha = 0.7, title.col = " ", palette = "PRGn", legend.col.show = FALSE) +
  tm_legend(outside = TRUE) +
  tm_add_legend(type = "symbol", shape = 21, labels = "Hypoxic site", col = "#AF8DC3", size = 0.4) +
  tm_add_legend(type = "symbol", shape = 21, labels = "Eutrophic site", col = "#7FBF7B", size = 0.4) +
  tm_layout(legend.title.size = 0.8, legend.title.fontface = "bold", frame = F) 


tmap_save(hyp_eut_map, filename = "../../Figs/hyp_eut_map.png", width = 6, height = 2.5, units = "in")
```


Get list of countries that have hypoxic, eutrophic and/or acidic conditions. 

```{r}
#suitable countries for seaweed
ctrys <- read_csv("~/github/seaweed/Data/sw_feasible_countries.csv")

#reading in the OHI EEZ shapefile from aurora and filtering just for EEZs while removing Antarctica
eezs <- read_sf(file.path(dir_a, "input/world_eezs/regions_2017_update.shp"), quiet = T) %>%
  filter(rgn_name %in% country) %>%
  st_transform(crs = 4326) %>%
  as('Spatial')


#intersect the sites with eezs

sites_int <- intersect(eezs, sites_sf)
```



